### ISSUE TITLE
Screen size properties don't change window size

### ISSUE THREAD

**Issue by Mengmoshu** [replit/play#13]
`play.screen.width` and `play.screen.height` can be changed, but don't change the window size (on Windows 10). They do influence the center of the coordinate system.

This means that for things running locally at least, the only possible window size is the default (800x600). That's pretty small by today's standards, and for my game will definitely start to either crowd my UI or compromise visual clarity.

Also, the shift of the coordinate system seems worse than doing nothing. Right now it moves 0,0 down and right.

**Comment by Glench** [comment]
Good catch! We'll definitely fix this.
