### ISSUE TITLE
Physics issues with play.screen dimensions

### ISSUE THREAD

**Issue by srbdev** [replit/play#14]
I believe there is a bug when I use the physics command and setting a custom window size.

```python
play.screen.width = 1280
play.screen.height = 720

ball = play.new_box(color='black', x=0, y=0, width=20, height=20)
ball.start_physics(can_move=True, stable=False, x_speed=10, y_speed=10, obeys_gravity=False, bounciness=1, mass=10, friction=0.1)

play.start_program()
```

The `ball` starts moving but still seems constrained by the default window size rather than the 1280x720 size I set up.

**Comment by Glench** [comment]
ooh, good catch! will fix
