### ISSUE TITLE
Support for basic shapes

### ISSUE THREAD

**Issue by srbdev** [replit/play#2]
Is support for basic shapes (circle, rectangle, line, etc.) planned for the future?

It seems like the current workaround would be to use sprites for the desired shapes but handling a color attribute wouldn't be straight forward, if possible.

**Comment by Glench** [comment]
We just added the `play.new_box()` command for making rectangles. Circles and lines are planned and coming soon.

**Comment by Glench** [comment]
Just added `play.new_circle()`. Check out the docs for how to use it. `play.new_line()` coming soon.

**Comment by srbdev** [comment]
Thank you for the quick turn around. I will need to check it out soon. Thanks again!

**Comment by Glench** [comment]
fixed in f80c87f!
