### ISSUE TITLE
ctrl-q and waiting for task

### ISSUE THREAD

**Issue by aoloe** [replit/play#4]
thanks for the ctrl-q.

i've tried it and it works!

but when quitting while the code in [What's with all this async/await stuff? Is this Python?](https://github.com/replit/play#whats-with-all-this-asyncawait-stuff-is-this-python) is running gives me a message in the terminal:

```
Task was destroyed but it is pending!
task: <Task pending coro=<repeat_forever.<locals>.repeat_wrapper() done, defined at /home/ale/src/dojo-resources/cards-python/play/venv/lib/python3.7/site-packages/play/play.py:723> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2ec4a14078>()]>>
```

for what i understand, everything is fine, but i wonder if there is a way to suppress the message...

**Comment by Glench** [comment]
fixed in c654923
